import type { AionProgram } from "../ir/types.js";

export function createStarterProgram(): AionProgram {
  return {
    aion: "0.1",
    kind: "system",
    metadata: {
      name: "starter-system",
      description: "A starter AION program generated by aion init.",
      version: "0.1.0",
      tags: ["starter"],
    },
    actors: [
      {
        id: "user",
        role: "human",
        description: "A human user who interacts with the system.",
      },
    ],
    entities: [
      {
        id: "message",
        description: "A simple starter entity.",
        fields: [
          { id: "id", type: "uuid", required: true },
          { id: "body", type: "string", required: true },
          { id: "created_at", type: "datetime", required: true },
        ],
      },
    ],
    operations: [
      {
        id: "message.create",
        intent: "Create a message.",
        actor: "user",
        reads: [],
        writes: ["message"],
        inputs: [{ id: "body", type: "string", required: true }],
        outputs: [{ id: "message_id", type: "uuid", required: true }],
        guards: ["body.length > 0"],
        effects: ["audit.log:message.create"],
        invariants: ["message.body must not be empty"],
        tests: ["reject empty body", "write audit log"],
      },
    ],
  };
}

export function createStarterProgramJson(): string {
  return `${JSON.stringify(createStarterProgram(), null, 2)}\n`;
}
